/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheHearthRouteImport } from './routes/the-hearth'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventPlanningRouteImport } from './routes/event-planning'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as BookingPoliciesRouteImport } from './routes/booking-policies'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesTheWeaveRouteImport } from './routes/stories.the-weave'
import { Route as StoriesTheFalconsRouteImport } from './routes/stories.the-falcons'
import { Route as StoriesMorungRouteImport } from './routes/stories.morung'
import { Route as StoriesKonyakRouteImport } from './routes/stories.konyak'
import { Route as StoriesJapfuRouteImport } from './routes/stories.japfu'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as HeritageProductsProductIdRouteImport } from './routes/heritage-products.$productId'

const TheHearthRoute = TheHearthRouteImport.update({
  id: '/the-hearth',
  path: '/the-hearth',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventPlanningRoute = EventPlanningRouteImport.update({
  id: '/event-planning',
  path: '/event-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPoliciesRoute = BookingPoliciesRouteImport.update({
  id: '/booking-policies',
  path: '/booking-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesTheWeaveRoute = StoriesTheWeaveRouteImport.update({
  id: '/the-weave',
  path: '/the-weave',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesTheFalconsRoute = StoriesTheFalconsRouteImport.update({
  id: '/the-falcons',
  path: '/the-falcons',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesMorungRoute = StoriesMorungRouteImport.update({
  id: '/morung',
  path: '/morung',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesKonyakRoute = StoriesKonyakRouteImport.update({
  id: '/konyak',
  path: '/konyak',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesJapfuRoute = StoriesJapfuRouteImport.update({
  id: '/japfu',
  path: '/japfu',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => StoriesRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageProductsProductIdRoute =
  HeritageProductsProductIdRouteImport.update({
    id: '/heritage-products/$productId',
    path: '/heritage-products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/booking-policies': typeof BookingPoliciesRoute
  '/booking-success': typeof BookingSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/event-planning': typeof EventPlanningRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/heritage': typeof HeritageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/the-hearth': typeof TheHearthRoute
  '/heritage-products/$productId': typeof HeritageProductsProductIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/japfu': typeof StoriesJapfuRoute
  '/stories/konyak': typeof StoriesKonyakRoute
  '/stories/morung': typeof StoriesMorungRoute
  '/stories/the-falcons': typeof StoriesTheFalconsRoute
  '/stories/the-weave': typeof StoriesTheWeaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/booking-policies': typeof BookingPoliciesRoute
  '/booking-success': typeof BookingSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/event-planning': typeof EventPlanningRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/heritage': typeof HeritageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/the-hearth': typeof TheHearthRoute
  '/heritage-products/$productId': typeof HeritageProductsProductIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/japfu': typeof StoriesJapfuRoute
  '/stories/konyak': typeof StoriesKonyakRoute
  '/stories/morung': typeof StoriesMorungRoute
  '/stories/the-falcons': typeof StoriesTheFalconsRoute
  '/stories/the-weave': typeof StoriesTheWeaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/booking-policies': typeof BookingPoliciesRoute
  '/booking-success': typeof BookingSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/event-planning': typeof EventPlanningRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/heritage': typeof HeritageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/stories': typeof StoriesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/the-hearth': typeof TheHearthRoute
  '/heritage-products/$productId': typeof HeritageProductsProductIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/japfu': typeof StoriesJapfuRoute
  '/stories/konyak': typeof StoriesKonyakRoute
  '/stories/morung': typeof StoriesMorungRoute
  '/stories/the-falcons': typeof StoriesTheFalconsRoute
  '/stories/the-weave': typeof StoriesTheWeaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/booking-policies'
    | '/booking-success'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/event-planning'
    | '/explore'
    | '/faq'
    | '/heritage'
    | '/privacy-policy'
    | '/reviews'
    | '/stories'
    | '/terms-and-conditions'
    | '/the-hearth'
    | '/heritage-products/$productId'
    | '/listings/$listingId'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/stories/japfu'
    | '/stories/konyak'
    | '/stories/morung'
    | '/stories/the-falcons'
    | '/stories/the-weave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/booking-policies'
    | '/booking-success'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/event-planning'
    | '/explore'
    | '/faq'
    | '/heritage'
    | '/privacy-policy'
    | '/reviews'
    | '/stories'
    | '/terms-and-conditions'
    | '/the-hearth'
    | '/heritage-products/$productId'
    | '/listings/$listingId'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/stories/japfu'
    | '/stories/konyak'
    | '/stories/morung'
    | '/stories/the-falcons'
    | '/stories/the-weave'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/booking-policies'
    | '/booking-success'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/event-planning'
    | '/explore'
    | '/faq'
    | '/heritage'
    | '/privacy-policy'
    | '/reviews'
    | '/stories'
    | '/terms-and-conditions'
    | '/the-hearth'
    | '/heritage-products/$productId'
    | '/listings/$listingId'
    | '/rooms/$roomId'
    | '/stories/$storyId'
    | '/stories/japfu'
    | '/stories/konyak'
    | '/stories/morung'
    | '/stories/the-falcons'
    | '/stories/the-weave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BookingPoliciesRoute: typeof BookingPoliciesRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EventPlanningRoute: typeof EventPlanningRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  HeritageRoute: typeof HeritageRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TheHearthRoute: typeof TheHearthRoute
  HeritageProductsProductIdRoute: typeof HeritageProductsProductIdRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-hearth': {
      id: '/the-hearth'
      path: '/the-hearth'
      fullPath: '/the-hearth'
      preLoaderRoute: typeof TheHearthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-planning': {
      id: '/event-planning'
      path: '/event-planning'
      fullPath: '/event-planning'
      preLoaderRoute: typeof EventPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-policies': {
      id: '/booking-policies'
      path: '/booking-policies'
      fullPath: '/booking-policies'
      preLoaderRoute: typeof BookingPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/the-weave': {
      id: '/stories/the-weave'
      path: '/the-weave'
      fullPath: '/stories/the-weave'
      preLoaderRoute: typeof StoriesTheWeaveRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/the-falcons': {
      id: '/stories/the-falcons'
      path: '/the-falcons'
      fullPath: '/stories/the-falcons'
      preLoaderRoute: typeof StoriesTheFalconsRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/morung': {
      id: '/stories/morung'
      path: '/morung'
      fullPath: '/stories/morung'
      preLoaderRoute: typeof StoriesMorungRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/konyak': {
      id: '/stories/konyak'
      path: '/konyak'
      fullPath: '/stories/konyak'
      preLoaderRoute: typeof StoriesKonyakRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/japfu': {
      id: '/stories/japfu'
      path: '/japfu'
      fullPath: '/stories/japfu'
      preLoaderRoute: typeof StoriesJapfuRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-products/$productId': {
      id: '/heritage-products/$productId'
      path: '/heritage-products/$productId'
      fullPath: '/heritage-products/$productId'
      preLoaderRoute: typeof HeritageProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoriesRouteChildren {
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesJapfuRoute: typeof StoriesJapfuRoute
  StoriesKonyakRoute: typeof StoriesKonyakRoute
  StoriesMorungRoute: typeof StoriesMorungRoute
  StoriesTheFalconsRoute: typeof StoriesTheFalconsRoute
  StoriesTheWeaveRoute: typeof StoriesTheWeaveRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesJapfuRoute: StoriesJapfuRoute,
  StoriesKonyakRoute: StoriesKonyakRoute,
  StoriesMorungRoute: StoriesMorungRoute,
  StoriesTheFalconsRoute: StoriesTheFalconsRoute,
  StoriesTheWeaveRoute: StoriesTheWeaveRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  BookingPoliciesRoute: BookingPoliciesRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EventPlanningRoute: EventPlanningRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  HeritageRoute: HeritageRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  StoriesRoute: StoriesRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TheHearthRoute: TheHearthRoute,
  HeritageProductsProductIdRoute: HeritageProductsProductIdRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
